"""remove next_check_at and last_check_status column

Revision ID: 1316ef73e625
Revises: a1b6fea2c6f8
Create Date: 2026-02-10 14:52:34.942747

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1316ef73e625"
down_revision: Union[str, Sequence[str], None] = "a1b6fea2c6f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("scheduler_index"), table_name="monitors")
    op.drop_column("monitors", "next_check_at")
    op.drop_column("monitors", "last_check_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monitors",
        sa.Column(
            "last_check_status", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "monitors",
        sa.Column(
            "next_check_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("scheduler_index"),
        "monitors",
        ["is_active", "next_check_at"],
        unique=False,
    )
    # ### end Alembic commands ###
