"""add_api_key_to_users

Revision ID: a1b6fea2c6f8
Revises: 84523c08cf3e
Create Date: 2026-01-27 11:55:45.768942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b6fea2c6f8'
down_revision: Union[str, Sequence[str], None] = '84523c08cf3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###
